# Generated by Django 2.1.2 on 2019-12-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='contenttype',
            name='description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(max_length=5000),
        ),
    ]
